/*
The New Life (RPG Mission)
Copyright (C) 2009  Matthew Simms & Petr Klíma
*/

#include "preDefine.hpp"
#include "dialogBase.hpp"
#include "db.hpp"
#include "shops.hpp"
#include "inventory.hpp"
#include "atm.hpp"
#include "licenses.hpp"
#include "wallet.hpp"
#include "trunk.hpp"
#include "vehicleMenu.hpp"
#include "keyChain.hpp"
#include "trade.hpp"
#include "interaction.hpp"
#include "animations.hpp"
#include "stats.hpp"
#include "generic.hpp"
#include "bank.hpp"
#include "factories.hpp"
#include "gasStations.hpp"
#include "corporations.hpp"
#include "stockMarket.hpp"
#include "calendar.hpp"
#include "mayor.hpp"
#include "taxes.hpp"
#include "laws.hpp"
#include "copMenu.hpp"
#include "phones.hpp"
#include "speedCam.hpp"
#include "saytexts.hpp"
#include "workplaces.hpp"
#include "playerShopsMenu.hpp"
#include "playerShops.hpp"
#include "employee.hpp"
#include "export.hpp"